### ISSUE TITLE
Update to Flutter 2.8 breaks package

### ISSUE THREAD

**Issue by jlnrrg** [m3uzz/icon_picker#3]
With Flutter 2.8 the package breaks the build with the following message:

```bash
ERROR: ../../../.pub-cache/hosted/pub.dartlang.org/icon_picker-2.0.1/lib/material_icons.dart:38:27: Error: Member not found: 'six_ft_apart'.
../…/lib/material_icons.dart:38
ERROR:     'six_ft_apart': Icons.six_ft_apart,
ERROR:                           ^^^^^^^^^^^^
Exception: Build process failed
```

**Comment by jlnrrg** [comment]
As a similar [package](https://github.com/Ahmadre/FlutterIconPicker/issues/35) fixed this issue already, I decided to switch to it for now.

**Comment by hslbetto** [comment]
The problem was with the internal icon collection, but the package accepts passing its own custom collection. That would fix it.
Anyway, the package is updated and fixed.
